stack:
 - go 1.12 amd64

install:
  - choco install nsis -pre

environment:
  BUILD_DIR: build\windows

before_build:
  - go version

build_script:
  - ps: $env:VERSION = $(git describe --tags --always)
  - cmd: |
      go build
      mkdir %BUILD_DIR%
      copy lsleases.exe %BUILD_DIR%
      copy LICENSE %BUILD_DIR%
      copy MANUAL.html %BUILD_DIR%
      copy build-scripts\windows\installer.nsi %BUILD_DIR%
      copy build-scripts\windows\amd64/nssm.exe %BUILD_DIR%
      copy build-scripts\windows\*.bat %BUILD_DIR%
      cd %BUILD_DIR%
      makensis installer.nsi
      dir

artifacts:
  - path: $(BUILD_DIR)\lsleases_$(VERSION)_win_installer.exe
    name: installer

deploy:
  description: 'Release'
  provider: GitHub
  auth_token:
    secure: qqn10ztf8r42lkErydQEdSw0Vho2EmB0/8PjVuBjvN+r4QLbg6OLgWAVm7aeykiF
  artifact: installer
  force_update: true