#+TITLE: lsleases Manual

* Intro

*lsleases* helps you to find dynamic assigned ip addresses
from any devices in your local network.

This package contains two executables:


** lsleases

 *lsleases* displays captured ip addresses.

 See the *lsleaes* [[lsleases.org][man page]] for more information.


** lsleasesd

 *lsleasesd* captures broadcast 'DHCP request' datagrams.

 See the *lsleasesd* [[lsleasesd.org][man page]] for more information.


* Source

** Build from source

TODO


** Project structure

 #+BEGIN_EXAMPLE
 .
 ├── build                   : build scripts
 ├── cmd
 │   ├── lsleases            : client programm
 │   └── lsleasesd           : daemon programm
 ├── docs                    : documentation
 ├── examples                : go library examples
 ├── pkg                     : modules
 │   ├── config              : configuration
 │   ├── cscom               : client server communication
 │   ├── daemon              : daemon (lsleasesd)
 │   ├── leases              : leases, history, cleanup
 │   └── sniffer             : network sniffer
 ├── README.org
 #+END_EXAMPLE


* Firewall

*lsleases* opens a network socket to captures broadcast 'DHCP request' datagrams.

If you have a firewall which blocks all incomming traffic, *lsleases* can't capture any packages.

To temporary allow incomming traffic on port 67 (DHCP) execute the following command.
#+BEGIN_SRC shell :eval no
sudo iptables -I INPUT -p udp --dport 67 -j ACCEPT
#+END_SRC


TOOD: describe how make the firewall rule persistent.
